image: golang:1.8

variables:
  REPO_NAME: gitlab.com/creichlin/pentaconta

stages:
  - test
  - build
  - deploy

test-project:
  stage: test
  script:
    - go get github.com/tools/godep
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - godep restore
    - go install gitlab.com/creichlin/pentaconta/testservices/...
    - godep go test ./...

build-project:
  stage: build
  script:
    - go get github.com/tools/godep
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME/
    - cd $GOPATH/src/$REPO_NAME
    - godep restore
    - mkdir -p $CI_PROJECT_DIR/artifacts
    - godep go build -o $CI_PROJECT_DIR/artifacts/pentaconta
  artifacts:
    paths:
      - artifacts/pentaconta

deploy-project:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y python-pip libyaml
    - pip install --upgrade awscli
