image: golang:1.8

variables:
  REPO_NAME: gitlab.com/creichlin/pentaconta

stages:
  - test
  - build

test-project:
  stage: test
  script:
    - go get github.com/tools/godep
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - godep restore
    - go install gitlab.com/creichlin/pentaconta/testservices/...
    - echo $CI_PROJECT_DIR
    - ls -la $CI_PROJECT_DIR/bin
    - godep go test $(go list ./... | grep -v /vendor/)

build-project:
  stage: build
  script:
    - go get github.com/tools/godep
    - mkdir -p $GOPATH/src/$REPO_NAME
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME/
    - mkdir -p $CI_PROJECT_DIR/artifacts
    - cd $GOPATH/src/$REPO_NAME
    - godep restore
    - godep go build -o $CI_PROJECT_DIR/artifacts/pentaconta
  artifacts:
    paths:
      - artifacts/pentaconta
